### PR TITLE
Brush v1 RFC

### PR DESCRIPTION
**Pull request by tmagik**
Rebase work to attempt to bring brushed motor support up to latest master. Not tested and mostly for commentary at this point.

### CODE REVIEW

**Comment by samuelsadok** [comment]
The new control loop architecture is actually not yet on the `master` branch, so it would be nice if you could rebase or retarget this to the `devel` branch. Here are some pointers on how to do this: https://github.com/odriverobotics/ODrive/pull/362#issuecomment-735913379

Apart from that I just saw that this PR adds three new axis states for brushed motor control. However setting the `motor_type` should already be sufficient and more suitable to arbitrate between brushed/brushless code paths. The firmware should look at this variable to select the corresponding control law and hook up the data paths accordingly.

**Review by blaquezzz — APPROVED** [review]

**Comment by tmagik** [comment]
Something is broken in the build on -devel on my Mac M1, while this changeset to -master at least compiles.

Is anyone seeing this on other platforms, or do I have some weird Mac-Arm specific tup bug?
```
 *** tup messages ***
 *** Command ID=683 failed with return value 1
*  89) arm-none-eabi-g++ -std=c++17 -Wno-register -c ./communication/communication.cpp
-D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -mthumb -mfloat-
abi=hard -Wno-psabi -Wall -Wdouble-promotion -Wfloat-conversion -fdata-sections -ffunction-sections -g
-DUSB_PROTOCOL_NATIVE -DUART_PROTOCOL_ASCII -O2 -IThirdParty/FreeRTOS/Source/include 
-IThirdParty/FreeRTOS/Source/CMSIS_RTOS -IThirdParty/CMSIS/Include -IThirdParty/CMSIS/Device/ST/STM32F7xx/Include 
-IThirdParty/CMSIS/Device/ST/STM32F4xx/Include -IThirdParty/STM32_USB_Device_Library/Core/Inc 
-IThirdParty/STM32_USB_Device_Library/Class/CDC/Inc -DHW_VERSION_MINOR=6 -DHW_VERSION_VOLTAGE=56 
-IBoard/v3/Inc -IBoard/v3/../../ThirdParty/FreeRTOS/Source/portable/GCC/ARM_CM4F -DSTM32F405xx 
-DHW_VERSION_MAJOR=3 -IThirdParty/STM32F4xx_HAL_Driver/Inc -DARM_MATH_CM4 -mcpu=cortex-m4 
-mfpu=fpv4-sp-d16 -DFPU_FPV4 -I./. -I./MotorControl -I./fibre/cpp/include
-o build/._communication_communication.cpp.o
Assembler messages:
Fatal error: can't create build/._communication_communication.cpp.o: No such file or directory
```

**Comment by tmagik** [comment]
@samuelsadok take a look at https://github.com/odriverobotics/ODrive/issues/545 ... do you have a mac to test with?

**Comment by samuelsadok** [comment]
yup, [fixed](https://github.com/odriverobotics/ODrive/issues/545#issuecomment-758272215).

**Comment by tmagik** [comment]
@samuelsadok  can you take a look at the results of https://github.com/tlalexander/ODrive/pull/1 (the history is... um, messy right now) , and see if this looks like the right direction?

I need to understand more of how foc.cpp is supposed to work...

**Comment by samuelsadok** [comment]
I'm not sure which of the 547 files to look at ;)

I would recommend cleaning up the history like this:
 1. pull the latest devel from the odriverobotics/ODrive repo and then push it to the tlalexander/ODrive repo.
 2. rebase the brushed motor feature onto the devel branch you just pushed using something like `git rebase -i devel`. When you do this, remove all commits that were not made by you. This part is important, because otherwise git might fail to detect some duplicate commits which can result in a huge changeset.

> I need to understand more of how foc.cpp is supposed to work...

Your brushed motor controller would not use foc.cpp but run instead of it. The arbitration between `FieldOrientedController` and `BrushedMotorController` would happen in the places that call `Motor::arm()` based on the configured motor type. Refer to [this header](https://github.com/odriverobotics/ODrive/blob/devel/Firmware/MotorControl/phase_control_law.hpp#L8) for documentation on the `PhaseControlLaw` interface. In addition you need to pass some input (e.g. voltage setpoint) to the BrushedMotorController. This can be done by implementing a function analogous to [FieldOrientedController::update()](https://github.com/odriverobotics/ODrive/blob/devel/Firmware/MotorControl/foc.cpp#L182-L191) and calling it from [ODrive::control_loop_cb()](https://github.com/odriverobotics/ODrive/blob/devel/Firmware/MotorControl/main.cpp#L447). The data source for such a voltage setpoint would be hooked up somewhere close to [here](https://github.com/odriverobotics/ODrive/blob/devel/Firmware/MotorControl/axis.cpp#L312-L314).

**Comment by tmagik** [comment]
@samuelsadok @tlalexander  I squashed it down to 1 commit in https://github.com/tmagik/ODrive/commit/178066382d4ba4abbf7590b3bf9d46e2a43f0bfa

**Comment by tmagik** [comment]
> Refer to this header for documentation on the PhaseControlLaw interface.

Is there a reason besides legacy support that the AlphaBetaFrameController has 3 phases and is not a template like PhaseControlLaw? I'm wondering how much refactoring would be necessary to consolidate the brake resistor into it's own 2-phase controller, and share code with a '2 phase' brush motor controller.

This then also leaves the question of what would a '1 phase' controller be, which I could imagine might be quite useful with an inductor to get a 'free' high-current switching power supply.

**Comment by rowanG077** [comment]
Good stuff! Can't wait until this is merged.

**Comment by samuelsadok** [comment]
> Is there a reason besides legacy support that the AlphaBetaFrameController has 3 phases and is not a template like PhaseControlLaw?

The FieldOrientedController+AlphaBetaFrameController follows traditional 3-phase motor control theory which is formulated for motors with exactly 3 phases. We have currently no use case to reformulate it for more general multiphase systems.

> I'm wondering how much refactoring would be necessary to consolidate the brake resistor into it's own 2-phase controller, and share code with a '2 phase' brush motor controller.

It's true that in an ideal design both the brushed motor controller and the brake resistor controller should be 2-phase controllers, however the integration of a `PhaseControlLaw<2>` with the underlying hardware would need to be well thought out because the reality is that the physical connectors for M0 and M1 have three phase legs. So it's easier for now to just implement the brushed motor controller as `PhaseControlLaw<3>`.

> This then also leaves the question of what would a '1 phase' controller be, which I could imagine might be quite useful with an inductor to get a 'free' high-current switching power supply.

Yes theoretically this would be possible with external hardware.

**Comment by sequoia-hope** [comment]
Thanks all. I originally authored these changes and I really appreciate @tmagik for his work bringing this up to master. My brushed branch is working nicely on the old code and at some point over the next year I would like to bring this up to master, but I don't know when I will have the time.

Incidentally I also have plans for a brushless linear motor that uses two hex bridges for operation, so having arbitrary control of the phases would be useful for that.

But just brushed control for now is still on my mind and I will try to get to this code when I can. My code has some hacks in it that would need to be addressed, which I could help with when I have time. Thanks all!

**Comment by Wetmelon** [comment]
As with #362, this needs to be updated again.  0.5.3 is not expected to change a lot, please update to that and open a clean PR if this is still desirable.

**Pull request closed without merging**
