### PR TITLE
Debug and flash for black magic probe

### PR DESCRIPTION
**Pull request by metanoic**
Been experimenting with a few different debuggers I got.  Enjoying the BMP in particular so far as it's much quicker than the ST-Link.  This PR includes changes to enable flashing and debugging with it.

Relies on setting an environment variable named `BMP_PORT` to the appropriate path.. e.g. `COM8` for Windows and `/dev/ttyACM0` for Linux.

The `bmp` makefile entry wasn't quite suitable as it leaves gdb open.  Figured an additional entry was in order so as not to step on the original work @sorki did.

**NOTE** the debug portion assumes `ARM_GCC_ROOT` env var exists a la #197

### CODE REVIEW

**Comment by metanoic** [comment]
Any word on getting this merged @madcowswe?

**Comment by emdash** [comment]
+1

**Comment by emdash** [comment]
I want to try to help get this merged, @metanoic, can you tell me how you physically connect the BMP? I have one, but have not used it much.

**Comment by sorki** [comment]
You need to connect SWDIO SWCLK (SWD, SWC pins on Odrive) and GND pins, possibly even VCC to 3V3 but you can also power via USB or external power.

**Comment by emdash** [comment]
What sort of cabling did you use? Im guessing you cut up the ribbon cable
maybe?

**Comment by sorki** [comment]
Yes even jumper cables are fine, preferably short as SVD is quite high frequency. For debugging with motor powered you will experience disconnects but it's possible to reconnect after initial spikes from startup are gone. It's also possible to use USB isolator to get rid of this.

**Pull request merged**
