### PR TITLE
replace "his" with "their" in HAL comments

### PR DESCRIPTION
**Pull request by driftregion**

### CODE REVIEW

**Comment by madcowswe** [comment]
Thanks for this, it's a great initiative and I approve. However this isn't our code, it is code that is coming out of the STM32CubeMX code generator. So I would suggest that you ask ST's "MCD Application Team" if they can incorporate these changes.

If you get a negative result from them, we can burn in these changes in our version of the codebase, but we have to do it via a special procedure to make sure it doesn't get overwritten when autogenerating the code again. Let me know how ST respond.

**Comment by driftregion** [comment]
Good, it's ticket 00077689 with ST support.  Also posted to twitter:
https://twitter.com/nick_kirkby/status/1120527218327859201

**Comment by driftregion** [comment]
ST Support answered with the following and closed the case.  I asked for follow-up with the STM32CubeMX team.
image

**Comment by driftregion** [comment]
image

**Comment by madcowswe** [comment]
Thanks for the update. Let's hope they implement this!

**Comment by camrbuss** [comment]
I hope ST does incorporate these changes, but should this PR be closed and let the pronoun change get merged in naturally when a CubeMX update gets brought in?

**Comment by madcowswe** [comment]
Yes this is not something we can do much about on this side, so I will close the PR.

**Pull request closed without merging**
