### PR TITLE
added control mode setters (current and velocity)

### PR DESCRIPTION
**Pull request by LuSeKa**
added functions in the Arduino library to set the ODrive control mode to either current or velocity

### CODE REVIEW

**Comment by madcowswe** [comment]
Thanks for making this.
What is the situation when you need to change the control mode, but you don't want to call SetVelocity or SetPosition to change into vel or pos mode?

**Comment by LuSeKa** [comment]
In my application (mobile robot control) I need the Arduino to change the ODrive's control mode between current and velocity. 
Does issuing SetVelocity() and SetCurrent() automatically change between these control modes? I might have overlooked this. 
If so, then separate setters for the control modes are probably unneccesary.

**Comment by Wetmelon** [comment]
> Does issuing SetVelocity() and SetCurrent() automatically change between these control modes? I might have overlooked this.

Yes, internal to the ODrive

**Comment by LuSeKa** [comment]
OK cool, I'll test

**Pull request closed without merging**
