### PR TITLE
Add support for UART_B on GPIO3/4

### PR DESCRIPTION
**Pull request by samuelsadok**
Adds support for UART_B on GPIO3 and GPIO4. UART_A (on GPIO1/2) and UART_B can currently not be enabled at the same time.

This supersedes #383.

HWIL Test Log:
e7f046d518a2670e025a1e09add10d593d548e9b: `uart_ascii_test.py` passes. With test-rig and test script modifications, `TestUartAscii` also passes on the new UART_B.
e15ab6018463f43f1b328e5e391fc20f9618a0e3: `uart_ascii_test.py`, `can_test.py`, `TestSpiEncoder(ENCODER_MODE_SPI_ABS_AMS)` and `TestSpiEncoder(ENCODER_MODE_SPI_ABS_CUI)` pass.

### CODE REVIEW

**Comment by SG-O** [comment]
When I try to 
execute odrv0.config.enable_uart1 = True 
I get the following error:

```
In [1]: odrv0.config.enable_uart1
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\Documents\GitHub\ODrive\Firmware\fibre\python\fibre\shell.py in <module>
----> 1 odrv0.config.enable_uart1

~\Documents\GitHub\ODrive\Firmware\fibre\python\fibre\remote_object.py in __getattribute__(self, name)
    243             return attr
    244         else:
--> 245             return object.__getattribute__(self, name)
    246             #raise AttributeError("Attribute {} not found".format(name))
    247

AttributeError: 'RemoteObject' object has no attribute 'enable_uart1'
```

**Comment by samuelsadok** [comment]
Whoops, looks like there was an error in the yaml, fixed now. I guess it must have sneaked in after testing but let me know if you have further problems.

**Comment by madcowswe** [comment]
Example of how to change active UART to GPIO 3/4:
```
odrv0.config.enable_uart0 = False
odrv0.config.gpio1_mode = GPIO_MODE_DIGITAL
odrv0.config.gpio2_mode = GPIO_MODE_DIGITAL
odrv0.config.enable_uart1 = True
odrv0.config.gpio3_mode = GPIO_MODE_UART1
odrv0.config.gpio4_mode = GPIO_MODE_UART1
odrv0.reboot()
```

**Comment by SG-O** [comment]
This fixed it for me! Thank you very much.
Also don't forget to run `odrv0.save_configuration()` 😄

**Comment by madcowswe** [comment]
@samuelsadok  Can you change it to be UART_A and UART_B instead?
Can you also add some instructions similar to [this](https://github.com/madcowswe/ODrive/pull/492#issuecomment-705828884) to the documentation?

**Comment by samuelsadok** [comment]
Done. I also changed similar user-facing names (SPI0 => SPI_A, I2C0 => I2C_A, CAN0 => CAN_A, PWM0 => PWM) and verified that the relevant HWIL tests pass.
**Edit:** forgot to update the docs. Will do that shortly (after syncing `devel` with the recent doc changes on `master`).

**Comment by SG-O** [comment]
When I get home, I'll test the changes.

**Pull request merged**
