### PR TITLE
Use environment variable for GNU Tools path

### PR DESCRIPTION
**Pull request by metanoic**
This PR changes the c/c++ Visual Studio Code extension's hardcoded paths for the GNU Tools Arm Embedded directory to an environment variable named ARM_GCC_ROOT.

### CODE REVIEW

**Comment by Wetmelon** [comment]
Can you add some information to the developers guide for Windows users explaining how to setup their environment variable for this?

**Comment by metanoic** [comment]
Added a step in the configuring-vscode doc instructing the user to create the environment variable.  Doesn't really belong in the developer's guide root doc as it only pertains to vscode and isn't Windows specific.

**Comment by Wetmelon** [comment]
This has been working really well for me on Windows.  Recommend accepting.

**Comment by madcowswe** [comment]
Thanks!

**Pull request merged**
