### PR TITLE
Fixed dockerbuild.sh

### PR DESCRIPTION
**Pull request by pbrier**
now run as user (instead of root) and fixed the autogeneration of `version.c`

### CODE REVIEW

**Comment by Wetmelon** [comment]
I don't see any issues with this.  You're using it locally I assume?

**Comment by pbrier** [comment]
Yes. This prevents 'root' owned files ending up in my directory. 
It does not seem to pass the Ubuntu 16.04 build step in CI. Can I see somewhere why it failed?

**Comment by samuelsadok** [comment]
Sorry, this closed automatically when deleting the target branch. If you want you can reopen it towards `fw-v0.5.5`. Ubuntu-16.04 is now removed from CI.

**Comment by madcowswe** [comment]
I fixed the branch delete issue by reinstating a `devel` branch. Thanks for your contribution.

**Pull request merged**
